use daemon threads in telemetryclient
paypay/newrelic-telemetry-sdk-java pull request #1
Opened 2020-05-27 12:32 UTC by vsanna

related issue: https://github.com/newrelic/newrelic-telemetry-sdk-java/issues/167

## Background
When TelemetryClient is getting 429 from NewRelic, it is caught into loop like below:

1. sendWithErrorHandling
2. retry
3. scheduleBatchSend
4. sendWithErrorHandling

In this flow, TelemetryClient doesn't consider maxRetries.

and this flow is executed in non-daemon threads(user threads), so while getting 429, TelemetryClient prevents JVM from shutting down.

This PR fixes the latter issue.

## Change
This PR just changes executor of TelemetryClient into one which uses ThreadFactory and set its threads as daemon threads.

2020-06-02 00:07 UTC, breedx-nr commented
Hi @vsanna .  I wanted to note that this PR is attempting to merge against your own fork.  For it to merge into [the upstream repo](https://github.com/newrelic/newrelic-telemetry-sdk-java) you will need to open a PR with [the master of this repo](https://github.com/newrelic/newrelic-telemetry-sdk-java) as the target.

Thanks thanks!

2020-06-02 23:10 UTC, breedx-nr requested changes
This looks good with just a few minor modifications.  Thank you for submitting this change!

2020-06-02 23:10 UTC, breedx-nr commented on telemetry/src/main/java/com/newrelic/telemetry/TelemetryClient.java
> +    this.shutdownSeconds = 3L;
I'm ok with overloading the constructor, but when doing so I believe that constructors should be chained and only have one that actually does work.  That is, this should call the other constructor and pass in the defaulted `shutdownSeconds`.  So, with that, I would change this constructor to:

```
this(metricBatchSender, spanBatchSender, eventBatchSender, DEFAULT_SHUTDOWN_SECONDS)
```

and promote 3L to a constant value.

2020-06-02 23:10 UTC, breedx-nr commented on telemetry/src/main/java/com/newrelic/telemetry/TelemetryClient.java
> +        LOG.error("interrupted graceful shutdown", e);
Should call Thread.currentThread().interrupt() inside the catch to reset the flag.

2020-06-03 02:15 UTC, vsanna commented
@breedx-nr thank you for your review, fixed according to your reviews.
let me open a PR for original repo

2020-06-03 06:00 UTC, shaopay commented on telemetry/src/main/java/com/newrelic/telemetry/TelemetryClient.java
> +  });
This diff changes the default behavior, I feel it's better to provide a way to configure this executor.

2020-06-03 08:37 UTC, shaopay approved these changes

2020-06-03 08:39 UTC, merged